### ISSUE TITLE
Themeing & redlining component variations needed for MultiWindow

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#349]
All components need to be redlined & themed. When all components are themed, we will redline those components.

Please put **your name** and **pr #** next to the task you're currently working on.

### Component tasks in priority order
- [x] Avatar @bcalvery #373 , there is a bug we need to fix #738 
- [x] Button redlining @bcalvery #336
- [x] Button themeing @bcalvery #381 
- [x] Chat @bcalvery #652
- [x] Divider @codepretty #338 
- [x] Header @bcalvery #427 
- [x] Icon redlining @codepretty 
- [x] Icon themeing @codepretty #384 
- [x] Input @notandrew  #361 
- [x] Segment @bcalvery 
- [x] Status @bcalvery #373, there is a bug we need to fix #738 -> fixed in #795
- [x] Text @codepretty #317 
- [x] Menu themeing @codepretty #708
- [ ] RadioGroup themeing @notandrew 
- [ ] Accordion themeing (deprioritized, back burner: #939)
- [ ] Attachment themeing @bcalvery 
- [ ] Popup themeing
- [ ] Label themeing
- [ ] List themeing
- [ ] Menu redlining
- [ ] RadioGroup redlining
- [ ] Accordion redlining
- [ ] Attachment redlining
- [ ] Popup redlining
- [ ] Label redlining
- [ ] List redlining

### Doc Site
- [x] ComponentExample.tsx background should change on theme switch @codepretty #316 
- [ ] (Low priority) theme switcher for each Component Example

**Comment by alinais** [comment]
fyi @levithomason , @jurokapsiar , @hughreeling , @codepretty , @notandrew

**Comment by codepretty** [comment]
We are doing Dark theme & Contrast theme at the same time, so it is unnecessary to keep 2 separate issues for this. Merged #298 into this issue.

**Comment by levithomason** [comment]
Pretty much done. Really though, design/ux are leading this effort now.
