### ISSUE TITLE
`createComponent` Follow-up

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#475]
### Steps
`createComponent` factory method was introduced by #472 
We need to start porting our components to be created using this approach and iterate on `createComponent`.

This will track items we need to follow-up on. **TODO**:

- [x] merge feat(slot): slot factory proposal #376
- [x] merge feat(utils): replace react-docgen with typescript #460
- [ ] porting existing components #494
- [ ] Unit Tests
- [x] adding documentation and examples
- [x] handle accessibility

@levithomason 
@kuzhelov 
@layershifter 
@miroslavstastny 

anything to add?

**Comment by jurokapsiar** [comment]
handle focus zone should be changed to "handle accessibility"

**Comment by levithomason** [comment]
We are replacing createComponent with something more powerful.
